import { RatioResultsInitialState } from './Results/RatioResults/InitialState';
import { CoreInitialState } from './Core/InitialState';
import { AnalyticsInitialState } from './Analytics/InitialState';
import { ServicesInitialState } from './Services/Services/InitialState';
import { MethodResultsInitialState } from './Results/MethodResults/InitialState';
import { LoadTestResultsInitialState } from './Results/LoadTestResults/InitialState';
import { LoadTestResultsHistoryInitialState } from './Results/LoadTestResultsHistory/InitialState';
import { MethodsInitialState } from './Methods/InitialState';
import { ScenariosInitialState } from './Services/Scenarios/InitialState';
import { ExceptionResultsInitialState } from './Results/ExceptionResults/InitialState';
import { CompareSettingsInitialState } from './Compares/CompareSettings/InitialState';
import { IntegrationsInitialState } from './Integrations/InitialState';
import { MethodResultsHistoryInitialState } from './Results/MethodResultsHistory/InitialState';
import { CompareResultWithResultsInitialState } from './Compares/CompareResultWithResults/InitialState';
import { CompareResultWithScenarioInitialState } from './Compares/CompareResultWithScenario/InitialState';
import { CompareResultWithAveragesInitialState } from './Compares/CompareResultWithAverages/InitialState';
import { CompareAveragesWithScenarioInitialState } from './Compares/CompareAveragesWithScenario/InitialState';
import { CompareMethodWithScenarioInitialState } from './Compares/CompareMethodWithScenario/InitialState';
import { CompareMethodResultsHistoryInitialState } from './Compares/CompareMethodResultsHistory/InitialState';
import { CompareLoadTestResultsHistoryInitialState } from './Compares/CompareLoadTestResultsHistory/InitialState';

export interface ReduxState {
  core: CoreInitialState;
  methods: MethodsInitialState;
  services: ServicesInitialState;
  scenarios: ScenariosInitialState;
  analytics: AnalyticsInitialState;
  integrations: IntegrationsInitialState;
  ratioResults: RatioResultsInitialState;
  methodResults: MethodResultsInitialState;
  compareSettings: CompareSettingsInitialState;
  loadTestResults: LoadTestResultsInitialState;
  exceptionResults: ExceptionResultsInitialState;
  methodResultsHistory: MethodResultsHistoryInitialState;
  loadTestResultsHistory: LoadTestResultsHistoryInitialState;
  compareResultWithResults: CompareResultWithResultsInitialState;
  compareMethodWithScenario: CompareMethodWithScenarioInitialState;
  compareResultWithScenario: CompareResultWithScenarioInitialState;
  compareResultWithAverages: CompareResultWithAveragesInitialState;
  compareAveragesWithScenario: CompareAveragesWithScenarioInitialState;
  compareMethodResultsHistory: CompareMethodResultsHistoryInitialState;
  compareLoadTestResultsHistory: CompareLoadTestResultsHistoryInitialState;
}
