version: "3.9"

services:
  api:
    image: nikitafilonov/load-testing-hub-api:latest
    ports: [ "13000:13000" ]
    env_file: [ .env.load-testing-hub ]
    depends_on:
      migrator:
        condition: service_completed_successfully
    container_name: api

  panel:
    image: nikitafilonov/load-testing-hub-panel:latest
    ports: [ "13100:13100" ]
    env_file: [ .env.load-testing-hub ]
    container_name: panel

  migrator:
    image: nikitafilonov/load-testing-hub-api:latest
    command: alembic upgrade head
    env_file: [ .env.load-testing-hub ]
    depends_on:
      postgres:
        condition: service_healthy
    container_name: migrator

  postgres:
    image: postgres:16-alpine
    ports: [ "5432:5432" ]
    volumes: [ postgres_data:/var/lib/postgresql/data ]
    environment:
      POSTGRES_DB: load_testing_metrics_db
      POSTGRES_USER: load_testing_metrics_user
      POSTGRES_PASSWORD: load_testing_metrics_password
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      retries: 5
      timeout: 3s
      interval: 5s
    container_name: postgres

volumes:
  postgres_data: