name: Build and Push Docker Image

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read

jobs:
  docker:
    uses: docker/github-builder/.github/workflows/build.yml@v1
    permissions:
      contents: read
      id-token: write
    with:
      output: image
      push: true
      platforms: linux/amd64,linux/arm64
      meta-images: nikitafilonov/load-testing-hub-panel
      meta-tags: |
        type=ref,event=tag
    secrets:
      registry-auths: |
        - registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
